import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import vplex from '../components/vplex.gif'
//import VideoPlayer from 'react-video-js-player'

//import rain from '../components/rain.mp4';
//  import * as firebase from "firebase/app";
//import firebase from '../initFirebase';
// import {db,stoeage,rdb} from '../initFirebase';
// import { initializeApp } from 'firebase/app'
// import { getStorage , ref } from "firebase/storage";
// import {getAnalytics} from 'firebase/analytics';
const VideoJs = () => {
  const videosrc = rain;
}
export default function Home() {
  return (
    <div  className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className="myvid">
    {/* <Image className={styles.image} layout='fill' src={vplex}></Image> */}
</div>

      <main className={styles.main}>
        <h1 className={styles.title}>
Hunting coder
        </h1>

        <p className={styles.description}>
          CODE FOR CODE HUNTING
        </p>
       <div className="blogs">
          <div className="blog">
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
            
  )
}
